name: Build and deploy to Eks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This workflow has only two jobs [infra preparation and image building- pushing to ecr]. Deploy to Kubernetes job is on its way.
# Notes: OpenIDConnect OIDC can be used to authenticate github to use aws resources instead of using aws access keys.

jobs:
  terraform-infra-wf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Format terraform
      run: terraform fmt -check
      continue-on-error: true

    - name: Apply Terraform Changes
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve


  build-wf:
    name: Build, tag and push to Amazon ECR
    runs-on: ubuntu-latest # configuring the runner which executes my jobs
    needs: terraform-infra-wf

    steps:
      - name: Checkout source
        uses: actions/checkout@v3 # telling the runner to use this action to copy my code to the runner file system

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        id: install
        # running testing before building image. Only tested images are built.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
        node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build and push Docker image # login to the docker CLI inside the runner
        env:
          IMAGE_TAG: ${{ github.sha }} # keep this and use another image tag for simplicity
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # storing the login to ecr step ito a variable so that docker can use it to push 
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        # docker tag $ECR_REPOSITORY:$IMAGE_TAG $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name : Deploy to Eks
      #   env:
      #     EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      #   run: | # update the kubeconfig to point to the eks cluster
      #     aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl apply -f k8s/service.yaml

  deploy-wf:
    name: Deploy to EKS
    runs-on: ubuntu-latest # each job needs own runner
    needs: build-wf
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name : update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name : update the deployment 
        run: |
         kubectl apply -f k8s/deployment.yaml
         kubectl apply -f k8s/service.yaml   

        # since both jobs are in the same workflow, it can reuse the githab sha.
        #  No need to authenticate and pull from ecr. replace the image and wait for the rollout
      - name: update the deployment image to latest build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/express-app-deployment express-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment/express-app-deployment
